### ISSUE TITLE
Cwrapper improvements

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1088]
Following new features need to be added.
- [x] `rational_get_mpq` - Similar to `integer_get_mpz` - #1110 
- [x] function to call that would indicate whether a component like MPFR or MPC is installed. - #1114 
- [x] `complex_double_get(double complex d, basic s)` - converts `std::complex<double>` inside basic to a C `complex double` - #1123

**Comment by ShikharJ** [comment]
@isuruf I would like to work on this issue.

**Comment by ShikharJ** [comment]
@isuruf I have added the first feature (locally), though I am clueless regarding the implementation of the second feature. Please guide me.

**Comment by isuruf** [comment]
second one should be something like `int symengine_have_component(const char *c)` where the input is `mpfr` or `mpc` or `flint` or `arb`. To check that these are installed you can use, `HAVE_SYMENGINE_MPFR` and similar macros

**Comment by ShikharJ** [comment]
@isuruf Wouldn't having bool as a return type be better?

**Comment by isuruf** [comment]
@ShikharJ, there's no `bool` type in C, only in C++.

**Comment by ShikharJ** [comment]
Oh! Thanks for clearing me up on that!

**Comment by ShikharJ** [comment]
@isuruf Where can I find the entire list of components to be checked?

**Comment by RiteshKB** [comment]
@isuruf  what needs to be done in third feature?

**Comment by ShikharJ** [comment]
@RiteshKB Sir, I have already started my work on that. See my comments above.

**Comment by isuruf** [comment]
Closed via #1110 #1114 and #1123. Thanks @ShikharJ for the work
